version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a

  format:
    desc: Format the code
    aliases: ["ruff"]
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix

  run:
    desc: Execute the command
    cmds:
      - poetry run python -m waag --help

  test:
    desc: Run tests
    cmds:
      - poetry run pytest
