version: '3'

dotenv: ['custom.env', 'default.env']

vars:
  AWESOME_FILE: '{{.AWESOME_FILE| default "../awesome-web-archiving/README.md"}}'
  BASE_IRI: http://awesome.org/iipc/
  INTEGRATION_GRAPH: graphs/awesome.ttl

  GIT_USER_NAME: Awesome Update Bot 🤖
  GIT_USER_EMAIL: aub@example.org
  GIT_COMMIT_MESSAGE: Update Awesome Graph and README


tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a

  install:
    desc: Install the project dependencies
    cmds:
      - poetry install

  install:kisumu:
    desc: Install kisumu to build the README.md
    cmds:
      - pipx install kisumu

  run:
    desc: Execute the command
    cmds:
      - poetry run python -m waag.cli --awesome-file {{.AWESOME_FILE}} --iri {{.BASE_IRI}} --output-dir graphs

  test:
    desc: Run tests
    cmds:
      - poetry run pytest

  format:
    desc: Format the code
    aliases: ["ruff"]
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix

  build:
    desc: Build the README
    cmds:
      - kisumu build -g {{.INTEGRATION_GRAPH}} -t templates/README.md.jinja -o README.md

  commit-and-push-data:
    desc: Commit and push all changes made to the graphs
    cmds:
      - |
        echo "commit-id-old=$(git rev-parse HEAD)" >> {{.GITHUB_OUTPUT}}
        git add {{.INTEGRATION_GRAPH}} README.md
        git -c user.name="{{.GIT_USER_NAME}}" -c user.email="{{.GIT_USER_EMAIL}}" commit -m "{{.GIT_COMMIT_MESSAGE}}" || echo ""
        echo "commit-id-new=$(git rev-parse HEAD)" >> {{.GITHUB_OUTPUT}}
        git push || echo ""

  ci:
    desc: The task to be executed by some continuous integration (ci) system
    cmds:
      - task: install
      - task: clone-awesome-list
      - task: run
      - task: build
      - task: commit-and-push-data