version: '3'

vars:
  AWESOME_FILE: ../awesome-web-archiving/README.md
  BASE_IRI: http://awesome.org/iipc/

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -a

  format:
    desc: Format the code
    aliases: ["ruff"]
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix

  run:
    desc: Execute the command
    cmds:
      - poetry run python -m waag.cli --awesome-file {{.AWESOME_FILE}} --iri {{.BASE_IRI}}

  test:
    desc: Run tests
    cmds:
      - poetry run pytest
