name: Awesome Graph Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'

env:
  AW_BRANCH: main
  AW_REPO: "iipc/awesome-web-archiving"
  WAAG_BRANCH: main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: arduino/setup-task@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v6
      with:
        ref: ${{ env.WAAG_BRANCH }}
        path: waag
    - uses: actions/checkout@v6
      with:
        repository: ${{ env.AW_REPO }}
        ref: ${{ env.AW_BRANCH }}
        path: aw
    - name: "⚙️ Run CI Tasks"
      id: ci_step
      working-directory: waag
      env:
        AWESOME_FILE: "${{ env.GITHUB_WORKSPACE }}/aw/README.md"
        GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: task ci
